name: Bonjour
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Check la version de maven
        run: mvn -v
      - name: Maven Package
        run: mvn package
      - name: Maven Compile
        run: mvn compile
